config/routes.rb
Rails.application.routes.draw do

	concern :imageable do
		resources :pictures, only: [:index, :show]
	end

	concern :admin_imageable do
		resources :pictures, except: [:show]
	end

	devise_for :users

	resources :testimonials, except: [:edit, :update, :destroy]

	resources :pages, :attractions, only: [:show]

	resources :flights, only: [:index, :show]

	resources :casinos, concerns: [:imageable], only: [:index, :show]

	resources :destinations, concerns: [:imageable], only: [:index, :show]

	resources :venues, path: :ships, concerns: [:imageable], only: [:index, :show] do
		resources :attractions, concerns: [:imageable], only: [:index]
	end

	resources :ports, :events, :cruises, concerns: [:imageable], only: [:index, :show]

	namespace :maps do
		resources :casinos, only: [:index, :show]
		resources :cruises, :destinations, only: [:show]
	end

	namespace :admin do
		get '/' => 'admin#index', as: :admin

		resources :admin, only: [:index]

		resources :pages, :pictures, :testimonials, except: [:show]

		resources :destinations, :casinos, :events, :cruises, :ports, :attractions, concerns: [:admin_imageable], except: [:show]

		resources :venues, path: :ships, concerns: [:admin_imageable], except: [:show]

		resources :flights, except: [:show] do
			collection { post :import }
		end

		resources :menu_items, except: [:show] do
			collection { post :sort }
		end

		get '/menus', to: "menu_items#index"
		get '/:id', to: "pages#show", as: 'short_page'
	end

	get '/:id', to: "pages#show", as: 'short_page'

	get '/robots.txt' => 'static_pages#robots'

	# root 'static_pages#index'
	root 'pages#root'

end

app/views/admin/pages/_form.html.erb
<%= form_for [:admin, @page] do |f| %>
<% if @page.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

	<ul>
		<% @page.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
</div>
<% end %>


<div class="form-group">
	<%#= f.label :title %>
	<%= f.text_field :title, class: 'form-control', placeholder: 'Page Title' %>
</div>
<div class="form-group">
	<div class="input-group">
		<%= content_tag :span, root_url, class: 'input-group-addon' %>
		<%#= f.label :slug %>
		<%= f.text_field :slug, class: 'form-control', placeholder: 'Permalink Slug' %>
	</div>
</div>

<div class="form-group">
	<%= f.label :content, 'Page Content' %>
	<%= f.text_area :content, class: 'froala_content form-control' %>
</div>

<div class="checkbox">
	<label>
		<%= f.check_box :container_layout -%> Container Layout
	</label>
</div>
<div class="checkbox">
	<label>
	<%= f.check_box :front_page -%> Front Page
	</label>
</div>

<div class="actions">
	<%= f.submit nil, class: 'btn btn-primary btn-lg' %>
</div>

<hr>

<div class="row">
	<div class="col-xs-6">
		<%= link_to 'View Page', short_page_path(@page), class: 'btn btn-info btn-sm btn-block' if @page.persisted? %>
	</div>
	<div class="col-xs-6">
		<%= link_to 'Cancel', admin_pages_path, class: 'btn btn-warning btn-sm btn-block' %>
	</div>
</div>

</div>

<% end %>

app/views/admin/pages/edit.html.erb
<%= render 'form' %>

<%= link_to 'Back', admin_pages_path %>

app/views/admin/pages/index.html.erb
<%= link_to 'New Page', new_admin_page_path, class: 'btn btn-primary' %>
<hr>

<div class="table-responsive">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Title</th>
				<th class="text-center">Front Page</th>
				<th>Last Updated</th>
				<th></th>
			</tr>
		</thead>

		<tbody>
			<% @pages.each do |page| %>
			<tr>
				<td><%= link_to fa_icon('pencil', text: page.title), edit_admin_page_path(page) %></td>
				<td class="text-center"><%= fa_icon('check-square-o') if page.front_page %></td>
				<td><%= page.updated_at %></td>
				<td>
				<%= link_to fa_icon('eye'), short_page_path(page), class: 'btn btn-xs btn-info' %>
				<%= link_to fa_icon('remove'), [:admin, page], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %>
				</td>
				<td>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>

<div class="pagination-container text-center">
	<%= paginate @pages %>
</div>

app/views/admin/pages/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', admin_pages_path %>