config/routes.rb
Rails.application.routes.draw do

	concern :imageable do
		resources :pictures, only: [:index, :show]
	end

	concern :admin_imageable do
		resources :pictures, except: [:show]
	end

	devise_for :users

	resources :testimonials, except: [:edit, :update, :destroy]

	resources :pages, :attractions, only: [:show]

	resources :flights, only: [:index, :show]

	resources :casinos, concerns: [:imageable], only: [:index, :show]

	resources :destinations, concerns: [:imageable], only: [:index, :show]

	resources :venues, path: :ships, concerns: [:imageable], only: [:index, :show] do
		resources :attractions, concerns: [:imageable], only: [:index]
	end

	resources :ports, :events, :cruises, concerns: [:imageable], only: [:index, :show]

	namespace :maps do
		resources :casinos, only: [:index, :show]
		resources :cruises, :destinations, only: [:show]
	end

	namespace :admin do
		get '/' => 'admin#index', as: :admin

		resources :admin, only: [:index]

		resources :pages, :pictures, :testimonials, except: [:show]

		resources :destinations, :casinos, :events, :cruises, :ports, :attractions, concerns: [:admin_imageable], except: [:show]

		resources :venues, path: :ships, concerns: [:admin_imageable], except: [:show]

		resources :flights, except: [:show] do
			collection { post :import }
		end

		resources :menu_items, except: [:show] do
			collection { post :sort }
		end

		get '/menus', to: "menu_items#index"
		get '/:id', to: "pages#show", as: 'short_page'
	end

	get '/:id', to: "pages#show", as: 'short_page'

	get '/robots.txt' => 'static_pages#robots'

	# root 'static_pages#index'
	root 'pages#root'

end

app/models/event.rb
class Event < ActiveRecord::Base

	include DatetimeFormat
	datetime_vars start_var: :start_at, end_var: :end_at

	include Content
	include Imageable

	default_scope { includes(:casino).order(start_at: :asc) }

	scope :future, -> { where("start_at > ?", Time.now ) }

	belongs_to :casino

	validates :casino_id, presence: true

	def date_span
		self.start_at.strftime("%b %d, %Y") + ' - ' + self.end_at.strftime("%b %d, %Y")
	end

	def icon
		'calendar'
	end

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::AdminController

	include EventsHelper

	include ImageableBuilder

	before_action :set_event, only: [:edit, :update, :destroy]
	before_action :set_nested_includes, only: [:new, :edit]

	def index
		@events = Event.all.page(params[:page])
	end

	def new
		@event = Event.new

		@event.pictures.build
	end

	def edit
		@event.pictures.build
	end

	def create
		@event = Event.new(event_params)

		respond_to do |format|
			if @event.save
				format.html { redirect_to edit_admin_event_path(@event), notice: 'Event was successfully created.' }
				format.json { render :show, status: :created, location: @event }
			else
				format.html { render :new }
				format.json { render json: @event.errors, status: :unprocessable_entity }
			end
		end
	end

	def update
		respond_to do |format|
			if @event.update(event_params)
				format.html { redirect_to edit_admin_event_path(@event), notice: 'Event was successfully updated.' }
				format.json { render :show, status: :ok, location: @event }
			else
				format.html { render :edit }
				format.json { render json: @event.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		@event.destroy
		respond_to do |format|
			format.html { redirect_to admin_events_url, notice: 'Event was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private

	def set_event
		@event = Event.find(params[:id])
	end

	def set_nested_includes
		@nested_includes = []
		@nested_includes << :pictures
	end

	def event_params
		params.require(:event).permit(:title, :casino_id, :start_string, :end_string, :content, pictures_attributes: picture_params)
	end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	before_action :set_event, only: [:show]

	def index
		# @events = @events_q.result.page(params[:page])
		@events = Event.all
		@background_image = 'bg-event.jpg'
	end

	def show
	end

	private
	
	def set_event
		@event = Event.find(params[:id])
	end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/_form.html.erb
<%= form_for [:admin, @event], html: {multipart: true} do |f| %>
<% if @event.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

	<ul>
		<% @event.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="form-group">
	<%= f.label :title %>
	<%= f.text_field :title, class: 'form-control' %>
</div>

<div class="form-group">
	<%= f.label :casino_id, 'Casino (Venue)' %>
	<div class="input-group">
		<%= f.collection_select :casino_id, Casino.all, :id, :name, {include_blank: 'Select Venue'}, class: 'form-control', id: 'select_casino' -%>
		<span class="input-group-btn">
			<%= link_to 'Add Venue', new_admin_casino_path, class: 'btn btn-warning', data: { confirm: 'You are leaving this page. Unsaved changes will be lost.' } -%>
		</span>
	</div>
</div>

<div class="form-group">
	<%= f.label :content %>
	<%= f.text_area :content, class: 'froala_content form-control' %>
</div>

<% usec = Time.now.usec -%>
<div class="row">
	<div class="col-sm-6">
		<div class="form-group">
			<%= render 'admin/admin/datepicker', f: f, field: :start_string, label: 'Event Start Time', dtp_class: 'start', usec: usec -%>
		</div>
	</div>
	<div class="col-sm-6">
		<div class="form-group">
			<%= render 'admin/admin/datepicker', f: f, field: :end_string, label: 'Event End Time', dtp_class: 'end', usec: usec -%>
		</div>
	</div>
</div>

<%= render 'admin/admin/nested_accordion', f: f, includes: @nested_includes -%>

<div class="actions">
	<%= f.submit nil, class: 'btn btn-primary btn-lg' %>
</div>
<% end %>

app/views/admin/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', admin_events_path %>

app/views/admin/events/index.html.erb
<%= link_to "New Event", new_admin_event_path(@event), class: 'btn btn-primary' %>
<hr>

<div class="table-responsive">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Title</th>
				<th>Venue</th>
				<th>Dates</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @events.reverse.each do |event| %>
			<tr>
				<td><%= link_to event.title, edit_admin_event_path(event) -%></td>
				<td><%= link_to event.casino.try(:name), edit_admin_casino_path(event.casino) -%></td>
				<td><%= event.date_span -%></td>
				<td>
					<%= link_to fa_icon('remove'), [:admin, event], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' -%>
				</td>
			</tr>
			<% end -%>
		</tbody>
	</table>
</div>

<div class="pagination-container text-center">
	<%= paginate @events %>
</div>

app/views/admin/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_events_path %>