config/routes.rb
Rails.application.routes.draw do

	concern :imageable do
		resources :pictures, only: [:index, :show]
	end

	concern :admin_imageable do
		resources :pictures, except: [:show]
	end

	devise_for :users

	resources :testimonials, except: [:edit, :update, :destroy]

	resources :pages, :attractions, only: [:show]

	resources :flights, only: [:index, :show]

	resources :casinos, concerns: [:imageable], only: [:index, :show]

	resources :destinations, concerns: [:imageable], only: [:index, :show]

	resources :venues, path: :ships, concerns: [:imageable], only: [:index, :show] do
		resources :attractions, concerns: [:imageable], only: [:index]
	end

	resources :ports, :events, :cruises, concerns: [:imageable], only: [:index, :show]

	namespace :maps do
		resources :casinos, only: [:index, :show]
		resources :cruises, :destinations, only: [:show]
	end

	namespace :admin do
		get '/' => 'admin#index', as: :admin

		resources :admin, only: [:index]

		resources :pages, :pictures, :testimonials, except: [:show]

		resources :destinations, :casinos, :events, :cruises, :ports, :attractions, concerns: [:admin_imageable], except: [:show]

		resources :venues, path: :ships, concerns: [:admin_imageable], except: [:show]

		resources :flights, except: [:show] do
			collection { post :import }
		end

		resources :menu_items, except: [:show] do
			collection { post :sort }
		end

		get '/menus', to: "menu_items#index"
		get '/:id', to: "pages#show", as: 'short_page'
	end

	get '/:id', to: "pages#show", as: 'short_page'

	get '/robots.txt' => 'static_pages#robots'

	# root 'static_pages#index'
	root 'pages#root'

end

app/views/layouts/admin/_nav.html.erb
<nav class="navbar navbar-vertical navbar-default" role="navigation">
	<!-- Brand and toggle get grouped for better mobile display -->
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" href="/admin">Admin Menu</a>
	</div>

	<!-- Collect the nav links, forms, and other content for toggling -->
	<div class="collapse navbar-collapse navbar-ex1-collapse">
		<ul class="nav navbar-nav">

			<%= content_tag :li, link_to('Pages', admin_pages_path) -%>
			<%= content_tag :li, link_to('Navigation Menu', admin_menu_items_path) -%>
			<hr>
			<%= content_tag :li, link_to('Destinations', admin_destinations_path) -%>
			<%= content_tag :li, link_to('Casinos', admin_casinos_path) -%>
			<hr>
			<%= content_tag :li, link_to('Cruises', admin_cruises_path) -%>
			<%= content_tag :li, link_to('Ports', admin_ports_path) -%>
			<%= content_tag :li, link_to('Ships', admin_venues_path) -%>
			<%= content_tag :li, link_to('Attractions', admin_attractions_path) -%>
			<%#= content_tag :li, link_to('Ships', '#admin_ships_path') -%>
			<hr>
			<%= content_tag :li, link_to('Events', admin_events_path) -%>
			<hr>
			<%= content_tag :li, link_to('Flights', admin_flights_path) -%>
			<hr>
			<%= content_tag :li, link_to('Testimonials', admin_testimonials_path) -%>

		</ul>
	</div><!-- /.navbar-collapse -->
</nav>