config/routes.rb
Rails.application.routes.draw do

	concern :imageable do
		resources :pictures, only: [:index, :show]
	end

	concern :admin_imageable do
		resources :pictures, except: [:show]
	end

	devise_for :users

	resources :testimonials, except: [:edit, :update, :destroy]

	resources :pages, :attractions, only: [:show]

	resources :flights, only: [:index, :show]

	resources :casinos, concerns: [:imageable], only: [:index, :show]

	resources :destinations, concerns: [:imageable], only: [:index, :show]

	resources :venues, path: :ships, concerns: [:imageable], only: [:index, :show] do
		resources :attractions, concerns: [:imageable], only: [:index]
	end

	resources :ports, :events, :cruises, concerns: [:imageable], only: [:index, :show]

	namespace :maps do
		resources :casinos, only: [:index, :show]
		resources :cruises, :destinations, only: [:show]
	end

	namespace :admin do
		get '/' => 'admin#index', as: :admin

		resources :admin, only: [:index]

		resources :pages, :pictures, :testimonials, except: [:show]

		resources :destinations, :casinos, :events, :cruises, :ports, :attractions, concerns: [:admin_imageable], except: [:show]

		resources :venues, path: :ships, concerns: [:admin_imageable], except: [:show]

		resources :flights, except: [:show] do
			collection { post :import }
		end

		resources :menu_items, except: [:show] do
			collection { post :sort }
		end

		get '/menus', to: "menu_items#index"
		get '/:id', to: "pages#show", as: 'short_page'
	end

	get '/:id', to: "pages#show", as: 'short_page'

	get '/robots.txt' => 'static_pages#robots'

	# root 'static_pages#index'
	root 'pages#root'

end

app/controllers/admin/cruises_controller.rb
class Admin::CruisesController < Admin::AdminController

	# include cruisesHelper

	include ImageableBuilder

	before_action :set_cruise, only: [:edit, :update, :destroy]
	before_action :set_nested_includes, only: [:new, :edit]

	def index
		@cruises = Cruise.all.page(params[:page])
	end

	def new
		if parent = Cruise.find_by(id: params[:clone])
			@cruise = parent.dup
			@cruise.port_of_calls = parent.port_of_calls.map(&:dup)
		else
			@cruise = Cruise.new
			3.times do
				@cruise.port_of_calls.build
			end
		end
	end

	def edit
		3.times do
			@cruise.port_of_calls.build if @cruise.port_of_calls.empty?
		end
	end

	def create
		@cruise = Cruise.new(cruise_params)

		respond_to do |format|
			if @cruise.save
				format.html { redirect_to edit_admin_cruise_path(@cruise), notice: 'Cruise was successfully created.' }
				format.json { render :show, status: :created, location: @cruise }
			else
				format.html { render :new }
				format.json { render json: @cruise.errors, status: :unprocessable_entity }
			end
		end
	end

	def update
		respond_to do |format|
			if @cruise.update(cruise_params)
				format.html { redirect_to edit_admin_cruise_path(@cruise), notice: 'Cruise was successfully updated.' }
				format.json { render :show, status: :ok, location: @cruise }
			else
				format.html { render :edit }
				format.json { render json: @cruise.errors, status: :unprocessable_entity }
			end
		end
	end

	def destroy
		@cruise.destroy
		respond_to do |format|
			format.html { redirect_to admin_cruises_url, notice: 'cruise was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private

	def set_cruise
		@cruise = Cruise.find(params[:id])
	end

	def set_nested_includes
		@nested_includes = []
		@nested_includes << :port_of_calls
	end

	def cruise_params
		params.require(:cruise).permit(:title, :venue_id, :start_string, :end_string, :content, pictures_attributes: picture_params, port_of_calls_attributes: [:id, :port_id, :start_string, :end_string, :_destroy])
	end

end

app/controllers/cruises_controller.rb
class CruisesController < ApplicationController

	before_action :set_cruise, only: [:show]

	def index
		@cruises = Cruise.all
		@background_image = 'bg-water.jpg'
	end

	def show
	end

	private

	def set_cruise
		@cruise = Cruise.find(params[:id])
	end

end

app/controllers/maps/cruises_controller.rb
class Maps::CruisesController < ApplicationController

	layout 'maps'

	before_action :set_cruise, only: [:show]

	def show
	end

	private

	def set_cruise
		@cruise = Cruise.find(params[:id])
	end

end

app/helpers/cruises_helper.rb
module CruisesHelper
end

app/helpers/maps/cruises_helper.rb
module Maps::CruisesHelper
end

app/views/cruises/_ports.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title text-center">Ports of Call</h3>
	</div>

	<div class="embed-responsive embed-responsive-map">
		<%= content_tag :iframe, nil, src: maps_cruise_path(@cruise), class: 'embed-responsive-item' %>
	</div>

	<div class="table-responsive">
		<table class="table table-striped table-condensed">
			<thead>
				<tr>
					<th>Port</th>
					<th>Arrival</th>
					<th>Departure</th>
				</tr>
			</thead>
			<tbody>
				<% @cruise.port_of_calls.each_with_index do |poc, index| -%>

				<%= content_tag :tr, class: 'port-of-call', data: {index: index} do -%>
				<td>
					<%= link_to poc.port.name, poc.port, data: {toggle: :modal, target: '#defaultModal'} -%>
				</td>
				<td><%= poc == @cruise.port_of_calls.first ? '-' : poc.arrives_at.to_formatted_s(:custom_long_ordinal) -%></td>
				<td><%= poc == @cruise.port_of_calls.last ? '-' : poc.departs_at.to_formatted_s(:custom_long_ordinal) -%></td>
				<% end -%>

				<% end -%>
			</tbody>
		</table>
	</div>
</div>

app/views/cruises/index.html.erb
<% content_for :pre_container do -%>
<%= render 'static_pages/parallax_header', text: 'Cruises', img_url: @background_image -%>
<% end -%>

<div class="row">
	<%= render 'layouts/featured_images', items: @cruises, heading: :title -%>
</div>

<div class="table-responsive">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Title</th>
				<th>Dates</th>
				<th>Venue</th>
			</tr>
		</thead>

		<tbody>
			<% @cruises.future.each do |cruise| %>
			<tr>
				<td><%= link_to cruise.title, cruise %></td>
				<td><%= cruise.date_span %></td>
				<td><%= link_to cruise.venue.name, venue_path(cruise.venue) %></td>
			</tr>
			<% end %>
		</tbody>
	</table>

</div>

app/views/cruises/show.html.erb
<% @page_header = @cruise.title -%>

<div class="row">

	<aside class="col-sm-4">
		<% if @cruise.pictures.any? -%>
		<figure class="thumbnail">
			<%= link_to image_tag(@cruise.pictures.first.image_url), cruise_pictures_path(@cruise), data: {toggle: :modal, target: '#defaultModal'} -%>
		</figure>
		<% else -%>
		<!-- default cruise image -->
		<% end -%>

		<div class="panel panel-default">
			<header class="panel-heading">
				<h4 class="panel-title text-center">Cruise Details</h4>
			</header>
			<div class="panel-body">
				<p>
					<strong>Ship:</strong>
					<%= link_to @cruise.venue.name, venue_path(@cruise.venue) %>
				</p>

				<p>
					<strong>Start at:</strong>
					<%= @cruise.start_at.to_formatted_s(:custom_long_ordinal) %>
				</p>

				<p>
					<strong>End at:</strong>
					<%= @cruise.end_at.to_formatted_s(:custom_long_ordinal) %>
				</p>

				<p>
					<%= link_to fa_icon('asterisk', text: 'Attractions'), venue_attractions_path(@cruise.venue), class: 'btn btn-default btn-block btn-sm', data: {toggle: :modal, target: '#defaultModal'} %>
				</p>
			</div>
		</div>

	</aside>

	<div class="col-sm-8">
		<%= @cruise.rendered_content %>

		<%= render 'ports' -%>
	</div>

</div>

<% if is_admin? -%>
<hr>
<%= link_to 'Edit', edit_admin_cruise_path(@cruise) %> |
<%= link_to 'Back', cruises_path %>
<% end -%>